# Generated by Django 4.1.1 on 2022-09-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='location',
            field=models.CharField(default='', max_length=256),
        ),
    ]
